name: build-release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
  
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: zip -r game.zip build node_modules public LICENSE package-lock.json package.json server.js
    - name: Pandoc checklist
      uses: docker://pandoc/latex:3.1
      with: 
        args: "-o Checklist.pdf docs/Checklist.md"
    - name: Pandoc solutions
      uses: docker://pandoc/latex:3.1
      with: 
        args: "-o Solutions.pdf docs/Solutions.md"
    - name: Pandoc technical
      uses: docker://pandoc/latex:3.1
      with: 
        args: "-o Technical.pdf docs/Technical.md"
    - run: zip -r docs.zip Checklist.pdf Solutions.pdf Technical.pdf
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          game.zip
          docs.zip

